### ISSUE TITLE
Can't sign in to our dolores

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/dolores-landingham-slack-bot#1]
I cannot sign in to http://dolores.comms.creativecommons.uk0.bigv.io:5000/. Can you please check, @robmyers ?

**Comment by robmyers** [comment]
I added you to the group you need to be in for signing in.

I'm sorry for not remembering to add you - this is a new system for me. :-)

**Comment by soohyunpae** [comment]
Thanks! Now it works. :)

**Comment by robmyers** [comment]
Yay! :-)
