### ISSUE TITLE
Larry

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/dolores-landingham-slack-bot#4]
Hi @robmyers 

I just tested joining Slack and it seems our dear welcome bot - ccbot (Larry) - is actually not welcoming new people. Could you take a look? And below is the message we wanted to be displayed to new members:

> Welcome to the Creative Commons Slack!
> 
> Here’s a quick guide on how to get started:
> Join the #intro channel and introduce yourself (your name, affiliation, area(s) of interest, and a link to your favorite CC licensed work!)
> Feel free to say hello :wave: in #general
> Find and join other channels relevant to you. Do you know that anyone can participate in any Network Platform even if they are NOT yet an official Member of the Network? Join #cc-openedu, #cc-copyrightreform, or #cc-openglam to find more about how you can participate in each Platform!
> If you are interested in becoming an official Member of CC’s Global Network, or have any questions about establishing a Chapter, ask @simeon or @claudio on Slack.
> Any other queries? Email us at  members-support@creativecommons.org and we will help you find an answer.
> 
> The Creative Commons Global Network is an open, safe and inclusive space fostering sharing and collaboration regardless of age, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.  Anyone who is part of the CC Global Network including those participating in this Slack channel is expected to follow our Code of Conduct for Contributors as our community guidelines. You can read it here: https://github.com/creativecommons/global-network-strategy/blob/master/docs/Global_Network_Membership_Charter.md#codes-of-conduct
> 
> Thank you for joining and Happy Creative Commoning!
 

I'm sorry I posted this here, but I was not sure which repo this issue should go.

Thank you for your help in advance! :)

**Comment by soohyunpae** [comment]
Hi @robmyers! Could you have a look at this please?

**Comment by soohyunpae** [comment]
Hi @robmyers ! 

I really appreciate if you can have a look at this issue.:)

And this is the google doc that includes all the details:
https://docs.google.com/document/d/1HnojVcHTyQBlkuvNNkQKk-9LLCJtP_dAfe1YB1Yq0f0/edit?usp=sharing

**Comment by robmyers** [comment]
OK we have a new greeter set up with this message.

I will delete this repository shortly.
